name: muscle
description: MUSCLE is a program for creating multiple alignments of amino acid or nucleotide sequences. A range of options are provided that give you the choice of optimizing accuracy, speed, or some compromise between the two
keywords:
  - msa
  - multiple sequence alignment
tools:
  - muscle:
      description: MUSCLE: multiple sequence alignment with high accuracy and high throughput
      homepage: https://www.drive5.com/muscle/
      documentation: http://www.drive5.com/muscle/muscle.html#_Toc81224840
      doi: "https://pubmed.ncbi.nlm.nih.gov/15034147/"
      licence: ['http://www.drive5.com/muscle/manual/license.html']

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: Input sequences for alignment must be in FASTA format
      pattern: "*.{fasta,fa,fna}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: Output alignemnt file in FASTA format
      pattern: "*.{afa,fasta,fa,fna}"
  - GCG MSF:
      type: file
      description: GCG Multiple Sequence File (MSF) alignment format (similar to CLUSTALW)
      pattern: "*.{msf}"
  - ClustalW:
      type: file
      description: ClustalW alignment format without base/residue numbering
      pattern: "*.{clw}"
  - Phylip:
      type: file
      description: PHYLIP multiple sequence alignment format (sequences can be sequential or interweaved depending on MUSCLE flag options)
      pattern: "*.{phyi}"
  - HTML:
      type: file
      description: HTML format colored alignment
        pattern: "*.{html}"

authors:
  - "@MGordon09"
